# Generated by Django 6.0.6 on 2026-08-06 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_child"),
        ("fleet", "0002_geofence_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={"verbose_name_plural": "children"},
        ),
        migrations.RemoveField(
            model_name="child",
            name="school",
        ),
        migrations.AddField(
            model_name="child",
            name="route",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="fleet.route",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="child",
            name="weekdays",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated day codes, e.g. MON,WED,FRI",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="child",
            name="name",
            field=models.CharField(max_length=150, verbose_name="First and Last name"),
        ),
    ]
