# Generated by Django 6.0.6 on 2026-08-06 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_alter_child_options_remove_child_school_child_route_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="pickup_hour",
        ),
        migrations.RemoveField(
            model_name="child",
            name="weekdays",
        ),
        migrations.CreateModel(
            name="ChildSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("pickup_hour", models.TimeField()),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="accounts.child",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
                "unique_together": {("child", "weekday")},
            },
        ),
    ]
