# Generated by Django 6.0.6 on 2026-08-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_child_pickup_hour_remove_child_weekdays_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="active_ride",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="child",
            name="active_ride_start",
            field=models.DateTimeField(null=True),
        ),
    ]
