# Generated by Django 6.0.6 on 2026-09-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_child_active_ride_child_active_ride_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="active_ride_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
