# Generated by Django 6.0.6 on 2026-09-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_parentinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_channel",
            field=models.CharField(
                choices=[("SMS", "Text message"), ("EMAIL", "Email")],
                default="SMS",
                max_length=10,
            ),
        ),
    ]
