# Generated by Django 6.0.6 on 2026-07-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_geofence_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_type', models.CharField(choices=[('in', 'Arrived'), ('out', 'Left')], max_length=12)),
                ('time', models.DateTimeField()),
                ('geo_fence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.geofence')),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.van')),
            ],
        ),
    ]
