# Generated by Django 6.0.6 on 2026-09-10 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_route_van'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('device_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='fleet.van')),
            ],
            options={
                'get_latest_by': 'device_time',
                'indexes': [models.Index(fields=['van', '-device_time'], name='tracking_po_van_id_3b1b5f_idx')],
            },
        ),
    ]
