# Generated by Django 6.0.6 on 2026-09-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="course",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
