# Generated by Django 6.0.6 on 2026-09-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_position_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
