# Generated by Django 6.0.6 on 2026-09-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_position_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="speed",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
