# Generated by Django 6.0.6 on 2026-07-14 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('location_type', models.CharField(choices=[('SCHOOL', 'School'), ('GYM', "Gina's Gymnastics")], default='SCHOOL', max_length=32)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.PositiveIntegerField(help_text='meters')),
                ('traccar_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Van plate number', max_length=20, unique=True)),
                ('tracker_imei', models.CharField(help_text="Tracker's IMEI number", max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='fleet.geofence')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='fleet.geofence')),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.van')),
            ],
        ),
    ]
