# Generated by Django 6.0.6 on 2026-07-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
