# Generated by Django 6.0.6 on 2026-08-07 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_geofence_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="van",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="routes",
                to="fleet.van",
            ),
        ),
    ]
